import * as fs from "fs";
import * as path from "path";

/** Founder rulings (AGENTS.md). Independent of the Rust crate so a 1.85% slip fails. */
export const FOUNDER = {
  MINT_PREMIUM_RATE_BPS: 125,
  UNDERLYING_PREMIUM_RATE_BPS: 100,
  PROTOCOL_PREMIUM_RATE_BPS: 25,
  TREASURY_MIN_PCT: 10,
  TREASURY_ACCEPT_PCT: 8,
  COMBINED_BACKING_MIN_PCT: 18,
  MAX_COMPUTE_UNITS: 1_400_000,
  NON_TRANSFERABLE_MINT_SPACE: 170,
  TRANSFER_FEE_MINT_SPACE: 278,
  SH2_MAX_SLIPPAGE_BPS: 50,
  SALE_PCT_MIN: 25,
  LP_PCT_MIN: 10,
  TRANSFER_FEE_DEFAULT_BPS: 50,
  FEE_LP_DEFAULT_BPS: 15,
  FEE_TREASURY_DEFAULT_BPS: 15,
  FEE_CTOKEN_RESERVE_BPS: 5,
  FEE_PROTOCOL_MIN_BPS: 15,
  REDEMPTION_TREASURY_FEE_BPS: 35,
  REDEMPTION_REVENUE_FEE_BPS: 15,
  LIQUIDATION_FEE_BPS: 200,
  LIQUIDATION_FEE_CTOKEN_BPS: 175,
  LIQUIDATION_FEE_PROTOCOL_BPS: 25,
} as const;

const CONSTANTS_RS = path.join(
  __dirname,
  "..",
  "crates",
  "transmuter-constants",
  "src",
  "lib.rs",
);

function rustU64(src: string, name: string): number {
  const m = src.match(new RegExp(`pub const ${name}: \\w+ = ([0-9_]+);`));
  if (!m) {
    throw new Error(`missing ${name} in transmuter-constants`);
  }
  return Number(m[1].replace(/_/g, ""));
}

export function readRustConstants() {
  const src = fs.readFileSync(CONSTANTS_RS, "utf8");
  return {
    MINT_PREMIUM_RATE_BPS: rustU64(src, "MINT_PREMIUM_RATE_BPS"),
    UNDERLYING_PREMIUM_RATE_BPS: rustU64(src, "UNDERLYING_PREMIUM_RATE_BPS"),
    PROTOCOL_PREMIUM_RATE_BPS: rustU64(src, "PROTOCOL_PREMIUM_RATE_BPS"),
    TREASURY_MIN_PCT: rustU64(src, "TREASURY_MIN_PCT"),
    TREASURY_ACCEPT_PCT: rustU64(src, "TREASURY_ACCEPT_PCT"),
    COMBINED_BACKING_MIN_PCT: rustU64(src, "COMBINED_BACKING_MIN_PCT"),
    MAX_COMPUTE_UNITS: rustU64(src, "MAX_COMPUTE_UNITS"),
    NON_TRANSFERABLE_MINT_SPACE: rustU64(src, "NON_TRANSFERABLE_MINT_SPACE"),
    TRANSFER_FEE_MINT_SPACE: rustU64(src, "TRANSFER_FEE_MINT_SPACE"),
    SH2_MAX_SLIPPAGE_BPS: rustU64(src, "SH2_MAX_SLIPPAGE_BPS"),
    SALE_PCT_MIN: rustU64(src, "SALE_PCT_MIN"),
    LP_PCT_MIN: rustU64(src, "LP_PCT_MIN"),
    TRANSFER_FEE_DEFAULT_BPS: rustU64(src, "TRANSFER_FEE_DEFAULT_BPS"),
    FEE_LP_DEFAULT_BPS: rustU64(src, "FEE_LP_DEFAULT_BPS"),
    FEE_TREASURY_DEFAULT_BPS: rustU64(src, "FEE_TREASURY_DEFAULT_BPS"),
    FEE_CTOKEN_RESERVE_BPS: rustU64(src, "FEE_CTOKEN_RESERVE_BPS"),
    FEE_PROTOCOL_MIN_BPS: rustU64(src, "FEE_PROTOCOL_MIN_BPS"),
    REDEMPTION_TREASURY_FEE_BPS: rustU64(src, "REDEMPTION_TREASURY_FEE_BPS"),
    REDEMPTION_REVENUE_FEE_BPS: rustU64(src, "REDEMPTION_REVENUE_FEE_BPS"),
    LIQUIDATION_FEE_BPS: rustU64(src, "LIQUIDATION_FEE_BPS"),
    LIQUIDATION_FEE_CTOKEN_BPS: rustU64(src, "LIQUIDATION_FEE_CTOKEN_BPS"),
    LIQUIDATION_FEE_PROTOCOL_BPS: rustU64(src, "LIQUIDATION_FEE_PROTOCOL_BPS"),
  };
}
